title: Sahaj Gupta
logo: /assets/img/cropped-head-shot2.png  # Ensure this image exists
theme: jekyll-theme-minimal
show_footer: false
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
